// Generated by Wrangler by running `wrangler types`

interface Env {
	KEY: "test-secret-key";
	NODE_ENV: "test";
	PRIVATE_KEY: "test-private-key";
	TOKEN_A_ADDRESS: "0x8f6fDE1B60e0d74CA7B3fD496444Dac2f2C7d882";
	TOKEN_B_ADDRESS: "0xafC9D020d0b67522337058f0fDea057769dd386A";
	BSC_RPC_URL: "https://bsc-dataseed.binance.org/";
	ETH_RPC_URL: "https://mainnet.infura.io/v3/test";
	POLYGON_RPC_URL: "https://polygon-rpc.com/";
	CORS_ORIGIN: "http://localhost:5173,http://localhost:3000";
	RATE_LIMIT_WINDOW_MS: "900000";
	RATE_LIMIT_MAX_REQUESTS: "100";
	R2: R2Bucket;
	DB: D1Database;
	AI: Ai;
}
